/**
 * Represents a Problem Details object as defined by RFC 7807.
 *
 * This interface models the standard members of the problem details
 * JSON object, plus an index signature for extension members that
 * allow APIs to attach domain-specific data.
 *
 * @see https://www.rfc-editor.org/rfc/rfc7807
 */
export interface IProblemDetail {
  /**
   * A URI reference [RFC3986] that identifies the problem type.
   * When dereferenced, it SHOULD provide human-readable documentation
   * for the problem type. When this member is not present, its value
   * is assumed to be "about:blank".
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type.
   * It SHOULD NOT change from occurrence to occurrence of the problem,
   * except for purposes of localization.
   */
  title: string;

  /**
   * The HTTP status code ([RFC7231], Section 6) generated by the
   * origin server for this occurrence of the problem.
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence
   * of the problem.
   */
  detail?: string;

  /**
   * A URI reference that identifies the specific occurrence
   * of the problem. It may or may not yield further information
   * if dereferenced.
   */
  instance?: string;

  /**
   * Extension members: APIs MAY extend the problem details object
   * with additional members to carry domain-specific data.
   */
  [key: string]: unknown;
}
